### PR TITLE
Add test support

### LINKED ISSUE #46: Support running tests through REPL
It would be great if the plugin would support running `clojure.test` tests (the whole namespace or individual `deftest`s) through the REPL.

Succeeding tests could be marked in the editor. See https://cursive-ide.com/userguide/testing.html for how this could look like.

Cursive  supports this, but sadly not yet as a default mode, cf. https://github.com/cursive-ide/cursive/issues/2770.

### LINKED ISSUE #48: Eval/load-file actions lock editor
When evaluating or loading a file that takes some time to eval, we can see that intellij freezes because we are sync waiting for nrepl response, we should add a progress bar + do that async.

### PR DESCRIPTION
**Pull request by ericdallo**
Fixes #48 
Fixes #46 

demo

- Add `run ns tests` action
- Add `run test at cursor` action
- When a test fail we show the new Clojure tests tool window
- Improve eval/load-file actions to run async avoid freezing

### CODE REVIEW

**Comment by ericdallo** [comment]
v0: [Uploading clojure-repl-0.1.6.zip…]()

**Comment by ericdallo** [comment]
v1:  [clojure-repl-0.1.6.zip](https://github.com/afucher/clojure-repl-intellij/files/14728634/clojure-repl-0.1.6.zip)

**Comment by ericdallo** [comment]
v3: add gutter icon to run tests
[clojure-repl-0.1.6.zip](https://github.com/afucher/clojure-repl-intellij/files/14749908/clojure-repl-0.1.6.zip)


image

**Comment by ericdallo** [comment]
v4: fix hint for older intellijs
[clojure-repl-0.1.6.zip](https://github.com/afucher/clojure-repl-intellij/files/14791013/clojure-repl-0.1.6.zip)

**Review by afucher — APPROVED** [review]
LGTM 🐗

**Pull request merged**
